# CONFIG

init: 1-1

# SCHEMA

# block-step:
#   intro: "some introductive text"
#   questions:
#     id_question_1:
#       text: "how old are you ?" # optional
#       format: integer|text|date|email|password|checkbox|select # mandatory
#       options: [A,B,C] # optional (options pour le select)
#       name: age # mandatory
#       label: "Your Age" # optional
#       default: 25 # optional
#      id_question_x ..............
#        format:....
#        name:...
#   info: "some informational text"
#   validate: "this will be the text on the form submit button"
#   next: 1-2|some_path # another step listed below or a route path

# TODO :
# - add validations on inputs
# - add JS live validations on inputs
# - fail ouputs (ex more than 5 people canno't use the service)
# - allow additional questions to appear in certain cases
# - todo allow to use variables from past responses in questions
# - allow to loop on several persons (for block 2,3,5)
# - separate init from the funnel : steps_init.yml & steps_funnel.yml ?
# - make questions optional

#########################

1-1:
  intro: ""
  questions:
    0:
      text: Dans quel arrondissement souhaitez-vous chercher votre futur appartement ?
      format: integer
      name: "candidate[dossier_zip]"
      label: Code postal
      default: 75011
  info: "Le prix et les attentes des propriétaires en terme de garantie dépendent du loyer, du type de bien et de leur localisation. Par exemple, dans tous les arrondissements de Paris, la demande est forte et les propriétaires peuvent donc être très exigeants. Un dossier clair et complet vous permet de gagner des places dans la file d'attente !"
  validate: Valider
  next: 1-2

1-2:
  intro: "Votre bail"
  questions:
    0:
      text: Combien de personnes seront sur le bail ? (vous inclus)
      format: integer
      name: "candidate[dossier_people]"
      label: Personne(s)
      default: 1
  info: "Dans un bail d'habitation, les différentes personnes sont collectivement responsables du règlement du loyer mensuel."
  validate: Valider
  next: 1-3


1-3:
  intro: ""
  questions:
    0:
      text: Montant maximum du loyer pour le bien recherché ? (pour toutes les personnes)
      format: integer
      name: "candidate[dossier_max_rent]"
      label: Loyer maximum
      default: 800€
  info: "L'INSEE recommande un loyer mensuel ne dépassant pas un tiers des revenus. C'est la norme généralement appliquée sur le marché par les agences et les propriétaires pour accepter les candidatures de locataires."
  validate: Valider
  persist: true
  next: pages_step2_path

2-1:
  intro:
  questions:
    0:
      text: "Faisons connaissance, utilisateur ID %:id% lol"
      format: text
      name: "candidate[firstname]"
      label: Prénom
    1:
      text:
      format: text
      name: "candidate[lastname]"
      label: Nom
    3:
      text:
      format: date
      name: "candidate[birthdate]"
      label: Date de naissance
    4:
      text:
      format: checkbox
      name: "candidate[cautioner]"
      label: A un garant ?
  info: ""
  validate: Bonjour!
  loop_if: is_populated_step2
  loop: 2-1
  next: pages_step3_path

3-1:
  intro:
  questions:
    0:
      text: Quelle est la situation de %:firstname% aujourd'hui?
      format: select
      options: ['CDI', 'Autre situation de travail (CDD, intérim, TNS)', 'Étudiant', 'Sans emploi']
      name: "candidate[status]"
      label: Situations
    # 2: # si CDI
    #   text: En période d'essai ?
    #   format: checkbox
    #   name: "candidate[try_period]"  # field does not exist yet !
    #   label: Période d'essai
  info: ""
  validate: valider
  next: 3-2

3-2:
  intro:
  questions:
    0:
      text: Quell est le revenu de %:firstname% aujourd'hui?
      format: integer
      name: "candidate[income]"
      label: Revenu mensuel net
      default: 1500€
  info: ""
  validate: valider
  next: 3-3

3-3:
  intro:
  questions:
    0:
      text: Quelle est la relation de %:firstname% avec son garant ?
      format: select
      options: ['Parent', 'Ami', 'Banque', 'Employeur']
      name: "candidate[cautioner_relationship]"
      label: Situation
    # #: # si parent
      # text: Quelle est le revenu du garant de %Prénom% aujourd'hui?
      # format: integer
      # name: "candidate[cautioner_income]" # field does not exist yet !
      # label: Revenu mensuel net
      # default: 1500€
  info: ""
  validate: valider
  loop_if: is_populated_step3
  loop: 3-1
  next: pages_step4_path


